default.bluepill[:bin] = "#{languages[:ruby][:gems_dir]}/bin/bluepill"
default.bluepill[:config_dir] = "/etc/bluepill"
default.bluepill[:log_dir] = "/var/log/bluepill"
default.bluepill[:pid_dir] = "/var/run/bluepill"
bluepill[:version] = "0.0.44"
